version: '3.4'

services:
  totvs-desafio:
    image: ${DOCKER_REGISTRY-}totvsdesafio
    build:
      context: .
      dockerfile: totvs-desafio/Dockerfile

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 32411680
      POSTGRES_USER: postgres
      POSTGRES_DB: totvs-desafio
    ports:
      - "5433:5432"

    